server:
  port: 8280
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudstudy?serverTimezone=GMT%2B8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
